version: '3.7'

services:

  jesse:
    image: salehmir/jesse:python38
    volumes:
      - ./data/jesse:/home
    depends_on:
      - db
    ports:
      - 8888:8888

  db:
    build:
      context: ./postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
